/apps/Arch/software/SciPy-bundle/2022.05-foss-2022a/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3474: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/apps/Arch/software/SciPy-bundle/2022.05-foss-2022a/lib/python3.10/site-packages/numpy/core/_methods.py:189: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
Traceback (most recent call last):
  File "/mimer/NOBACKUP/groups/naiss2023-6-336/assolito/./masks_selection.py", line 137, in <module>
    lung_mask = make_lungmask(patient_volume)
  File "/mimer/NOBACKUP/groups/naiss2023-6-336/assolito/mask_creation.py", line 33, in make_lungmask
    kmeans = KMeans(n_clusters=2).fit(np.reshape(middle, [np.prod(middle.shape), 1]))
  File "/apps/Arch/software/scikit-learn/1.1.2-foss-2022a/lib/python3.10/site-packages/sklearn/cluster/_kmeans.py", line 1367, in fit
    X = self._validate_data(
  File "/apps/Arch/software/scikit-learn/1.1.2-foss-2022a/lib/python3.10/site-packages/sklearn/base.py", line 577, in _validate_data
    X = check_array(X, input_name="X", **check_params)
  File "/apps/Arch/software/scikit-learn/1.1.2-foss-2022a/lib/python3.10/site-packages/sklearn/utils/validation.py", line 909, in check_array
    raise ValueError(
ValueError: Found array with 0 sample(s) (shape=(0, 1)) while a minimum of 1 is required by KMeans.
